[package]
name = "rsbind-build-script"
version = "0.1.0"
edition = "2021"
description = "build script for rsbind."
license = "Apache-2.0"

[dependencies]
zip = "0.5.13"
walkdir = "2.3.2"

[lib]
name = "build_script"
path = "src/lib.rs"

