use_frameworks!

platform :ios, '9.0'

target 'demo-ios_Example' do
  pod 'rustlib', :path => '../rustlib/_gen/ios_artifact'
end

target 'demo-ios_ExampleTests' do
  pod 'rustlib', :path => '../rustlib/_gen/ios_artifact'
end
