[package]
name = "demo_ios_bridge_prj"
version = "0.1.0"
authors = ["sidney.wang <sidney.wang@foxmail.com>"]

#[workspace]
#members = []

[lib]
crate-type = [ "lib", "staticlib" ]

[dependencies]
demo = { path = "../../"}
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"

[features]
