name: Test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  java-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup-Env
        run: cargo install --no-default-features --force cargo-make && cargo make setup-android-env
      - name: Unit-Test
        run: cd toolchain/rsbind && cargo test
      - name: Build-Android-Demo
        run: cargo make test-android-demo
      - name: Test-Jar-Demo
        run: cargo make test-jar-demo
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: my-artifact
    #     path: demo-jar/app/

  swift-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup-Env
        run: cargo install --no-default-features --force cargo-make && cargo make setup-ios-env
      - name: Unit-Test
        run: cd toolchain/rsbind && cargo test
      - name: Build-ios-Demo
        run: cargo make test-ios-demo
      - name: Test-Mac-Demo
        run: cargo make test-mac-demo