name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-android:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup-Env
      run: rustup target add aarch64-linux-android arm-linux-androideabi armv7-linux-androideabi i686-linux-android x86_64-linux-android
    - name: Build-Rust
      run: cd demo-android/rustlib && pwd && cargo run --manifest-path ../../toolchain/rsbind/Cargo.toml . android all
    - name: Build-Demo
      run: cd demo-android && pwd && ./gradlew assembleDebug
    
  build-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build-Rust
      run: cd demo-ios/rustlib && cargo run --manifest-path ../../toolchain/rsbind/Cargo.toml . ios all
 #   - name: Build-Demo
 #     run: cd ../Example && pod install && xcodebuild build -workspace demo-ios.xcworkspace -scheme demo-ios-Example
