name: Build

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-android:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup-Env
      run: rustup target add aarch64-linux-android arm-linux-androideabi armv7-linux-androideabi i686-linux-android x86_64-linux-android
    - name: Build-Rust
      run: cd demo-android/rustlib && pwd && cargo run --manifest-path ../../toolchain/rsbind/Cargo.toml . android all
    - name: Build-Demo
      run: cd demo-android && pwd && ./gradlew assembleDebug
    
  build-ios:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup-Env
      run: rustup target add aarch64-apple-ios x86_64-apple-ios
    - name: Build-Rust
      run: cd demo-ios/rustlib && cargo run --manifest-path ../../toolchain/rsbind/Cargo.toml . ios all
    - name: Pod-Install
      run: cd demo-ios/Example && pod install
    - name: Build-Demo
      run: xcodebuild -workspace "demo-ios/Example/demo-ios.xcworkspace" -scheme "demo-ios-Example" -sdk iphonesimulator -configuration "Debug" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" ARCHS="x86_64" clean build
