name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-android:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build-Rust
      run: cd demo-android/rustlib && cargo run --manifest-path ../../toolchain/rsbind/Cargo.toml . android all
    - name: Build-Demo
      run: cd .. && ./gredlew assembleDebug
    
